# Generated by Django 3.2.6 on 2021-08-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_rename_usuario_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizusuario',
        ),
    ]
