# Generated by Django 3.2.6 on 2021-08-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0010_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.quizusuario'),
        ),
    ]
